---
abstract: 'Skip some test files'
author:
  - 'David Golden <dagolden@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
  File::Spec: '0'
  File::Spec::Functions: '0'
  File::pushd: '0'
  List::Util: '0'
  Scalar::Util: '0'
  Test::FailWarnings: '0'
  Test::More: '0.96'
  version: '0.77'
configure_requires:
  ExtUtils::MakeMaker: '6.17'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.019, CPAN::Meta::Converter version 2.141170'
license: apache
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: TAP-Harness-Restricted
no_index:
  directory:
    - t
    - xt
    - examples
    - corpus
  package:
    - DB
provides:
  TAP::Harness::Restricted:
    file: lib/TAP/Harness/Restricted.pm
    version: '0.003'
requires:
  Path::Tiny: '0'
  TAP::Harness: '3.18'
  perl: '5.008001'
  strict: '0'
  superclass: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/dagolden/TAP-Harness-Restricted/issues
  homepage: https://github.com/dagolden/TAP-Harness-Restricted
  repository: https://github.com/dagolden/TAP-Harness-Restricted.git
version: '0.003'
x_authority: cpan:DAGOLDEN
x_contributors:
  - 'Dagfinn Ilmari Mannsåker <ilmari@ilmari.org>'
